# Generated by Django 4.2 on 2026-02-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('pct_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('territory_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('md_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pct_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prms_site.territory')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('MedRep', 'MedRep')], max_length=10)),
                ('pct_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prms_site.territory')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField()),
                ('rx_count', models.PositiveSmallIntegerField()),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms_site.account')),
                ('md_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms_site.prescriber')),
            ],
            options={
                'unique_together': {('md_code', 'employee_id', 'date_time_created')},
            },
        ),
    ]
